;!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="2b9c1067-a33e-478a-b66a-5cd355db63c0",e._sentryDebugIdIdentifier="sentry-dbid-2b9c1067-a33e-478a-b66a-5cd355db63c0")}catch(e){}}();import { a as $$Main, b as $$H1, c as $$BaseLayout } from './404_Lc-3aH9C.mjs';
import { e as createAstro, f as createComponent, r as renderTemplate, j as renderComponent, m as maybeRenderHead } from '../astro_2WJtSRFU.mjs';
import 'kleur/colors';
import 'clsx';
import { d as create_ssr_component } from './_slug__2dC7f6M1.mjs';
import { z } from 'zod';

z.object({
  comment: z.string().min(3, { message: "Is 3 characters really all you had to say?" }).max(255, { message: "Please use 255 characters or less" })
});

/* C:/Users/isimm/code/astro/james-quick/rythm-nation-blog/src/components/ContactForm.svelte generated by Svelte v4.2.8 */

const ContactForm = create_ssr_component(($$result, $$props, $$bindings, slots) => {

	return `<form novalidate class="grid gap-y-2"><label for="comment" class="text-zinc-900 text-2xl mb-2 mt-10" data-svelte-h="svelte-11sdp4">What&#39;s on your mind?</label> <textarea name="comment" id="comment" rows="3" required maxlength="255" class="border border-teal-900 rounded-lg text-2xl px-6 py-6"></textarea> ${``} <button type="submit" class="text-2xl text-zinc-100 bg-teal-900 px-6 py-5 rounded-xl my-1" data-svelte-h="svelte-55san0">Send</button></form>`;
});

const $$Astro = createAstro("https://rhythm-nation-blog.vercel.app");
const $$Contact = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Contact;
  return renderTemplate`${renderComponent($$result, "BaseLayout", $$BaseLayout, { "title": "Contact - Rhythm Nation", "description": "Contact us", "image": "/images/drums.jpg" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Main", $$Main, {}, { "default": ($$result3) => renderTemplate` ${renderComponent($$result3, "H1", $$H1, { "text": "Contact" })} ${maybeRenderHead()}<div class="mb-20"> ${renderComponent($$result3, "ContactForm", ContactForm, { "client:load": true, "client:component-hydration": "load", "client:component-path": "~/components/ContactForm.svelte", "client:component-export": "default" })} </div> ` })} ` })} `;
}, "C:/Users/isimm/code/astro/james-quick/rythm-nation-blog/src/pages/contact.astro", void 0);

const $$file = "C:/Users/isimm/code/astro/james-quick/rythm-nation-blog/src/pages/contact.astro";
const $$url = "/contact";

export { $$Contact as default, $$file as file, $$url as url };
//# sourceMappingURL=contact_oS59izny.mjs.map
